networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1

services:
  # 開啟兩個服務，模擬分布式部署
  web1: &web
    image: my-web-app:latest
    container_name: web1
    ports:
      - "5000:80"
    networks:
      default:
        ipv4_address: 172.18.1.10
    depends_on:
      - database
      - redis
      - nginx
 
  web2:
    <<: *web
    container_name: web2
    ports:
      - "5001:80"
    networks:
      default:
        ipv4_address: 172.18.1.11
    
  database:
    image: mysql:8.4.3
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: Asia/Shanghai
      MYSQL_CHARACTER_SET_SERVER: utf8
    ports:
      - "3306:3306"
    volumes:
      - D:\docker_volumn\mysql:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.1.2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - D:\docker_volumn\redis:/data
    networks:
      default:
        ipv4_address: 172.18.1.3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - D:\docker_volumn\nginx\nginx.conf:/etc/nginx/nginx.conf
    networks:
      default:
        ipv4_address: 172.18.1.4

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "13308:80"
    networks:
      default:
        ipv4_address: 172.18.1.5
        

  