name: ssh

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use 20
            cd shopping-website 
            docker compose stop
            git pull origin dev
            npm install
            npm run migrate  
            docker build -t my-web-app .
            docker build -t my-consumer-app -f ./kafka/Dockerfile .
            docker rmi -f `docker images | grep  "<none>" | awk '{print $3}'`
            docker compose restart